version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: rag-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@rag-postgres:5432/database164
      - CHAT_HISTORY_DATABASE_URL=postgresql+psycopg://postgres:postgres@rag-postgres:5432/pdf_rag_history
    ports:
      - "8000:8000"
    volumes:
      - ./pdf-documents:/code/pdf-documents
    networks:
      - rag-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  rag-network:
    driver: bridge
